### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by CATower** [DrEtad/intro-data-capstone-musclehub#3]
Great job, your presentation looks nice and you got all the correct answers.

Scores:
Code: 4/4 - all the graphs are correct, as well as the chi squared analysis
Hypothesis: 3/4 - Could have been a bit wordier in explaining what was being tested for, but still got the point across
Interpretations: 4/4 - Correctly interpreted the chi square tests and concluded what conservationists should focus on.
Presentation: 4/4 - looks nice, easy to read and gets the points across well

Overall 15/16 - Exceeds expectations. Congratulations on completing the intensive!

**Comment by DrEtad** [comment]
Thanks
